import sys
import os
from __main__ import selLegend

if selLegend == "Jhin":
    legPortrait = "jhin.PNG"
    p = "Jhin has 4 shots before a ‘Reload’ (1 turn in which you cannot\nauto attack) occurs. However, Jhin’s 4th shot deals DOUBLE\ndamage. Being out of combat will automatically reload. Jhin\nmay also attack Enemies at any range with his auto attacks."
    qt = int(3) #q cd
    qd = int(145) #q damage
    qm = int(20) #q mana cost
    wt = int(3) #w cd
    wd = int(190) #w damage
    wm = int(30) #w mana cost
    et = int(3) #e cd
    ed = int(260) #e damage
    em = int(20) #e mana cost
    rt = int(6) #r cd
    rd = int(200) #r damage
    rm = int(80) #r mana cost
    lad = int(100) #base AD
    lap = int(20) #base AP
    lspd = int(220) #base speed
    lhp = int(1000) #health
    lhpr = int(20) #health regen
    lm = int(100) #mana
    lmr = int(10) #mana regen
    lar = int(0) #armor
if selLegend == "Kayn":
    legPortrait = "kayn.JPG"
    p = "Kayn has access to 2 forms; Red and Blue. Red Kayn is obtained\nby gaining 800+ Max HP, and Blue is obtained by gaining 180+\nADDITIONAL Attack Damage."
    qt = int(4) #q cd
    qd = int(155) #q damage
    qm = int(30) #q mana cost
    wt = int(4) #w cd
    wd = int(270) #w damage
    wm = int(20) #w mana cost
    et = int(3) #e cd
    ed = int(0) #e damage
    em = int(10) #e mana cost
    rt = int(20) #r cd
    rd = int(350) #r damage
    rm = int(60) #r mana cost
    lad = int(100) #base AD
    lap = int(20) #base AP
    lspd = int(220) #base speed
    lhp = int(1000) #health
    lhpr = int(20) #health regen
    lm = int(100) #mana
    lmr = int(10) #mana regen
    lar = int(0) #armor
if selLegend == "Shen":
    legPortrait = "shen.PNG"
    p = "In progress..."
    qt = int(4) #q cd
    qd = int(0) #q damage
    qm = int(50) #q mana cost
    wt = int(6) #w cd
    wd = int(0) #w damage
    wm = int(15) #w mana cost
    et = int(2) #e cd
    ed = int(0) #e damage
    em = int(10) #e mana cost
    rt = int(20) #r cd
    rd = int(0) #r damage
    rm = int(50) #r mana cost
    lad = int(100) #base AD
    lap = int(20) #base AP
    lspd = int(220) #base speed
    lhp = int(1000) #health
    lhpr = int(20) #health regen
    lm = int(100) #mana
    lmr = int(10) #mana regen
    lar = int(0) #armor
if selLegend == "Zed":
    legPortrait = "zed.PNG"
    p = "In progress..."
    qt = int(3) #q cd
    qd = int(220) #q damage
    qm = int(15) #q mana cost
    wt = int(4) #w cd
    wd = int(0) #w damage
    wm = int(30) #w mana cost
    et = int(2) #e cd
    ed = int(170) #e damage
    em = int(15) #e mana cost
    rt = int(10) #r cd
    rd = int(100) #r damage
    rm = int(40) #r mana cost
    lad = int(100) #base AD
    lap = int(20) #base AP
    lspd = int(220) #base speed
    lhp = int(1000) #health
    lhpr = int(20) #health regen
    lm = int(100) #mana
    lmr = int(10) #mana regen
    lar = int(0) #armor
